Generating GIFs
Python version:
Python 3.7.12
CUDA visible devices:
0
CUDA version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__2_19:15:15_PDT_2021
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0
03:36:18 - INFO Loading model and transforms.
03:36:20 - INFO Loading diffusion noise model
03:36:20 - INFO Loading dataloader
03:36:20 - INFO Loading metrics
03:36:20 - INFO Loading diffusion wrapper model.
03:36:20 - INFO Created a temporary directory at /tmp/tmpa0zwaq5u
03:36:20 - INFO Writing /tmp/tmpa0zwaq5u/_remote_module_non_scriptable.py
03:36:20 - INFO Preparing data.
03:36:20 - INFO preparing batch.
03:36:22 - INFO Starting diffusion process
  0%|          | 0/200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "ovito_complete_gif.py", line 82, in <module>
    main()
  File "ovito_complete_gif.py", line 79, in main
    generate_samples(args)
  File "ovito_complete_gif.py", line 64, in generate_samples
    log_strs = diffusion_process_log(ex_batch, posttransform, args.diffusion_timesteps, args.t_skips, diffusion_model, fixed_noises)
  File "ovito_complete_gif.py", line 13, in diffusion_process_log
    log_strs = save_graph_str_batch(batch_dict, posttransform, [])
  File "/home/dvf755/graph-diffusion-project/code/diffusion/utils/plots.py", line 111, in save_graph_str_batch
    assert len(log_strs) == len(strs)
AssertionError
  0%|          | 0/200 [00:06<?, ?it/s]